# XRTK Azure Pipelines build configuration

resources:
  repositories:
    - repository: pipeline_repo
      type: github
      name: XRTK/AzurePipelines
      endpoint: XRTK

variables:
  project.name: 'XRTK.XRUX'
  project.upmSha: ''
  package.name: 'com.xrtk.xrux'
  package.version: ''
  EditorPath: ''
  LogDirectory: ''
  ${{ if eq( variables['build.reason'], 'PullRequest' ) }}:
    date: ''
  ${{ if ne( variables['build.reason'], 'PullRequest' ) }}:
    date: ${{ '$(Date:yyyyMMdd)' }}
  isReleaseBuild: $[ and( eq(variables['Build.SourceBranchName'], 'master'), or( eq(variables['build.reason'], 'BatchedCI'), eq(variables['build.reason'], 'Manual') ) ) ]
  isPreviewBuild: $[ and( eq(variables['System.PullRequest.TargetBranch'], 'master'), eq(variables['build.reason'], 'PullRequest') ) ]

name: $(package.name) ${{ coalesce( variables['date'], '$(System.PullRequest.PullRequestNumber)', '$(Date:yyyyMMdd)' ) }}$(Rev:.r)

pr:
  autoCancel: true
  branches:
   include:
     - master
     - development
     - feature/*
  paths:
    include:
    - azure-pipelines.yml
    - XRTK.XRUX/*
    - Submodules/*
    exclude:
      - '*'
      - XRTK.XRUX/Packages/com.xrtk.xrux/package.json
      - XRTK.XRUX/Packages/com.xrtk.xrux/README.md
      - XRTK.XRUX/Packages/com.xrtk.xrux/LICENSE.md

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines.yml
      - XRTK.XRUX/*
      - Submodules/*
    exclude:
      - '*'
      - XRTK.XRUX/Packages/com.xrtk.xrux/package.json
      - XRTK.XRUX/Packages/com.xrtk.xrux/README.md
      - XRTK.XRUX/Packages/com.xrtk.xrux/LICENSE.md

extends:
  template: common.yml@pipeline_repo
  parameters:
    # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
    # StandaloneWindows64, WSAPlayer, StandaloneOSX, iOS, StandaloneLinux64, Android, WebGL, Lumin
    # TODO: Only use XRTK defined platform targets for build
    targets:
      - StandaloneWindows64
      - WSAPlayer
      - StandaloneOSX
      - StandaloneLinux64
      - Android
      - WebGL
